### ISSUE TITLE
Unable to Connect

### ISSUE THREAD

**Issue by NW27** [Fourflies/elrsbuddy#1]
Hi, I tried your website (https://fourflies.mooo.com/elrsbuddy/) on a RadioMaster Ranger Tx. I'm having some issues with the connection. After hitting Pair, It shows a list of Serial Ports, I select the required one and then attempt to Connect. Below is the log

5008 device 4292:60000 paired
5468 error connecting to port: NetworkError Failed to execute 'open' on 'SerialPort': Failed to open serial port.
7843 device 4292:60000 unpaired
9234 device 4292:60000 paired
10361 error connecting to port: NetworkError Failed to execute 'open' on 'SerialPort': Failed to open serial port.

I have downloaded your code and tried running the index.html file locally on my PC (Win11). It visually looks ok but pressing the "Pair Button" doesn't bring up a list of available com ports.

**Comment by tzshin** [comment]
I encountered a similar issue when trying to connect to a "rx as tx" receiver. I switched between multiple USB serial adapters—some worked, while others didn't. It's worth noting that the ELRS serial baud rate requirement is quite demanding at 400k baud.

To solve this, I made a custom adapter using a Teensy 4.0, and it worked perfectly afterward.

**Comment by Fourflies** [comment]
@NW27 I replied to you on YouTube, but I'll just repeat here: please try reload the website again. It should display v1.0.1 now, with a change that hopefully will resolve the issue you experienced.

@tzshin Although 400 kbps has worked in my limited testing, a number of other users have reported problems. I was advised to use 921600 bps, which is apparently well supported. This is what v1.0.1 uses.

If 921600 bps still gives issues, I think I will need to add a baud selection field. I'd prefer to avoid that if possible, for simplicity.

Thanks for your feedback, both of you!

**Comment by NW27** [comment]
Hi,
In the web browser, I now get:
779 device 4292:60000 paired
1473 connected to port
1473 serial worker started

I must be missing some instruction somewhere.
I would have thought after establishing the connection, that I would be 
prompted or a web page button revealed for up loading of the 
"elrsV3.lua" file onto the Tx module, which it then some how passes 
through the appropriate config parameters to the Rx module.
I'm interested in this for setting up the Tx and Rx modules as a Airport 
connection and controlling the plane via a PC and USB port.

Thanks,
Neil.

P.S. Very new to ExpressLRS and drones/planes etc.

**Comment by Fourflies** [comment]
@NW27 The elrsV3.lua script is hosted on the web server and is downloaded automatically by elrsbuddy when the page loads. When you click connect, the elrsV3.lua "run" entry point gets executed.

From the log you pasted, it looks like elrsbuddy is working for you.

**Comment by NW27** [comment]
But that is all that's on the Web page. Nothing like what is on your 1st YouTube video 3 months ago.Kind regards, Neil Wrightson 
-------- Original message --------From: Fourflies ***@***.***> Date: 13/8/24  6:44 pm  (GMT+10:00) To: Fourflies/elrsbuddy ***@***.***> Cc: Neil Wrightson ***@***.***>, Mention ***@***.***> Subject: Re: [Fourflies/elrsbuddy] Unable to Connect (Issue #1) 
@NW27 The elrsV3.lua script is hosted on the web server and is downloaded automatically by elrsbuddy when the page loads. When you click connect, the elrsV3.lua "run" entry point gets executed.
From the log you pasted, it looks like elrsbuddy is working for you.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Fourflies/elrsbuddy/issues/1#issuecomment-2285696427",
"url": "https://github.com/Fourflies/elrsbuddy/issues/1#issuecomment-2285696427",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Fourflies** [comment]
@NW27 Ok, I see you said you're connecting a Radiomaster Ranger transmitter module. I assume you're connecting it to the PC using the Ranger's builtin USB port.

I think you haven't remapped the crossfire interface to the builtin USB port yet. I've been meaning to explain that step as its rather crucial. The USB ports in transmitter modules are usually configured as console ports, so out the box the USB port isn't usable for crossfire and elrsbuddy. I'll make a video soon describing how to correct that.

**Comment by Fourflies** [comment]
Hey @NW27, did you see my latest video upload? Let me know if you're still struggling to connect, otherwise I think I can close this issue. Thanks for your feedback.
